id: P004214
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30084
  title: རྗེ་ཡབ་སྲས་ཀྱི་གསུང་རྩོམ་ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    e0cc648a903241c399fd19259c92680a:
      image_group_id: I5798
      title: ''
      volume_number: 1
      total_pages: 562
      base_file: v001.txt
